---
title: "I am really pissed"
author: "Lucas C. Lima"
date: '2019-05-21'
slug: i-am-really-pissed
tags: ["academia"]
categories: ["personal"]
---

I am really pissed, let me tell you why. 

# the banner quest

I'm at this congress in Fortaleza - Ceará - Brazil [^1] and it was really *not* helpful on my research. I'm studying cosmetics rheology and most of the lectures were about asphalt and binding agents for pavements. That put aside I've had to create a banner out of thin air within 24 hours to present my work that i found out that was indeed accepted like i mentioned on the last post [__Failure__](https://comsemassim.netlify.com/2019/05/20/failure/) 


My adviser replied my email with some corrections 3 hours after i had sent it to him and so i had the task to correct it and have it printed by the next morning, which i obviously did because i don't want to be remembered as the guy who doesn't do what it takes. So I made it and it was not __THAT__ bad, at least from a design point of view. 

the next day i presented my banner to ONE person but more about that later, went back home and slept 'cus i had an early flight the next morning.

# the flight quest

I got one hour before my flight and it happened that my flight and all flights of the air company had been canceled. Well ok, I'll just reschedule it right? Wrong, there was no one at the company's ticket office. One hour passed and still no one. I had lost my flight.

A couple of minutes later some of the folks who where at the cue started calling their respective travel agencies and see if they could've sort that out for them so i did the same. I waited for a whole hour on the phone before i could talk to a human being that was ready to listen to my problems.

This human being told me to find this woman that worked for the travel agency and was dealing with the delays and reallocation and whatnot, but she told everyone that other air companies had no obligation to accommodate passengers and it was indeed very possible that no one would get flights that day. On top of that the only way to get an accommodation with another flight company was if the attendant of my air company filled the accommodation forms. And there was no attendant.

Eventually I got through the travel agency (after waiting for an hour on the phone) and they told me to stand by my phone and wait. By then the attendant had arrived an gathered a list of all passengers (around 36) with the same problem. She was going to use the list to ask for the other companies for reallocations. By the time she got back from the first round of what i assume was begging to the managers of other flight companies i got a call from my travel agency with a flight number and a voucher for a check-in.



> "Praised be the gods --- i thought"



The problems were the following:

  - I had to wait 4 more hours for my flight;
  - It was with one of the worst (if not the worst) air companies in Brazil;
  - I hadn't eaten anything;
  - I had 2 connections;
  - I was going to get to my hometown at 01:30 am the next day with no one to pick me up.
  
Luckily something good out of everything happened. I had been staying with my gf's uncle and when he heard what had happened he offered to take me to know a little bit of the city since i hadn't had[^2] the opportunity.

So i wet back to his home and he wasn't there but that was ok because there was a bar on the corner and i figured the only way i was going to get through this day was by getting at least a couple of beers. He arrived and we went to the beach. I swam and i dove and i had fun and i was great but i had to face 8 hours of flights. A note, I am 2 meters tall, so you can imagine me flying for 8 hours in coach.

# the summary

I'm writing this on the airplane on my way to São Paulo (the second flight out of 3), and it is very much crammed. I got lucky and got as isle seat but that doesn't help much on a 3-hour flight. I'm hopping to get on the airport and eat something and try to stretch my legs, but it seems to be a long way from now.


[^1]: I'll figure out how to add a `leaflet` map eventually
[^2]: *hadn't hads* are even better