---
title: "Failure"
author: "Lucas C. Lima"
date: '2019-05-20'
slug: failure
tags: ["frustration"]
categories: ["personal"]
---

Today I failed. I'm not used to failing, usually I'm pretty good at stuff and honestly I'm very dissapointed at myself.

Let me give you some context. I am a master's student and I'm at a congress right now. What happened is that I had had [^1] submitted an abstract to the scientific committe and it was accepted in the __abstract__ category. It wasn't clear if I shoul make a banner of an presentation so I sent an email to the organizing committee and received no reply, a week later I sent another email and still no response. Anyway, a couple of weeks later here I am across the country in the congress without a banner exactly as I intended. 

I get here and people ar putting their banners up and I ask one of them...

>"How did you get the confirmation that you should've bring a banner?"

and she responded:

>"When my abstract was accepted I started making it"

Am I that stupid?? Is it just me that didn't get the cue??

So I talked to my advisor and explained the situation and offered myself to make a poster in the 4 hours that I had this afternoon, so I sat my ass on the chair and started working on it. Of course it was no easy task and that is why I'm writing this post. 

If I hadn't failed this would not be happening. I sent it to my advisor with no hopes of it being accepted, but I tried. I tried really hard and I still couldn't make it.

Now I'm sitting at the couch watching *Friends* thinking about my failures and why I suck at everything. but being realistic I tried my best and have no regrets.

It's important to fail occasionally. It helps to keep us grounded and realize that we should always be thriving for greatness it helps to make us have the perception that nothing should come easily. I'm happy I failed, and I'll take this oportunity to learn to always have a plan B.

[^1]: I absolutely love using *had had*